version: '3.3'

volumes:
  ckan:
  solr:
  postgres:

networks:
  vpc:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.0.0/16
        gateway: 10.10.0.1

services:
  ckan:
    container_name: ckan
    image: ckan
    build:
      context: ./ckan/
    expose:
    - 80
    ports:
    - 80:80
    networks:
      vpc:
        ipv4_address: 10.10.0.2
    environment:
    # Environment Specific
    - CKAN_PORT=80
    - POSTGRES_FQDN=postgres
    - REDIS_FQDN=redis
    - SOLR_FQDN=solr
    - DATAPUSHER_FQDN=datapusher
    - CKAN_SITE_URL=http://sba.ckan.com
    - CKAN_DATAPUSHER_CALLBACK_URL=http://sba.ckan.com
    - CKAN_SMTP_ERROR_MAIL_TO=devops@sba.ckan.com
    - CKAN_SMTP_ERROR_MAIL_FROM=errors@sba.ckan.com
    - CKAN_SMTP_MAIL_FROM=admin@sba.ckan.com
    - SMTP_FQDN=smtp
    - SMTP_PORT=1025
    # Secrets
    - APP_UUID=AAAAAAAA-0000-1111-2222-BBBBBBBBBBBB
    - CKAN_API_TOKEN_SECRET=9OzsqKgYG4o_-6RGZ14ebdsh6
    #- CKAN_GOOGLE_ANALYTICS_ID=UA-000000-1
    - CKAN_SMTP_PASSWORD=fake
    - CKAN_SMTP_USER=fake
    - POSTGRES_PASSWORD=fearless
    - SESSION_SECRET=AAAAAAAAAAAAAAAAAAAAAAAAA
    volumes:
    - ckan:/var/lib/ckan/
    ## AWS Configuration: uncomment this line and ensure you have your AWS credentials configured in your local ~/.aws directory
    #- ~/.aws/:/root/.aws/

  datapusher:
    container_name: datapusher
    image: ckan-datapusher
    build:
      context: ./ckan-datapusher/
    expose:
    - 8800
    ports:
    - 8800:8800
    networks:
      vpc:
        ipv4_address: 10.10.0.3
    extra_hosts:
    - sba.ckan.com:10.10.0.2

  postgres:
    container_name: postgres
    image: postgres:11.1
    environment:
    - POSTGRES_PASSWORD=fearless
    - POSTGRES_USER=ckan_default
    - POSTGRES_DB=ckan_default
    expose:
    - 5432
    networks:
      vpc:
        ipv4_address: 10.10.0.4
    volumes:
    - postgres:/var/lib/postgresql/data/

  solr:
    container_name: solr
    image: ckan-solr
    build:
      context: ./ckan-solr/
    expose:
    - 8983
    ports:
    - 8983:8983
    networks:
      vpc:
        ipv4_address: 10.10.0.5
    volumes:
    - solr:/opt/solr/server/solr/ckan/data/

  redis:
    container_name: redis
    image: redis:latest
    expose:
    - 6379
    ports:
    - 6379:6379
    networks:
      vpc:
        ipv4_address: 10.10.0.6

  smtp:
    image: reachfive/fake-smtp-server
    expose:
    - 1025
    - 1080
    ports:
    - 1025:1025
    - 1080:1080
    networks:
      vpc:
        ipv4_address: 10.10.0.7
    command: ["node", "index.js", "--auth", "fake:fake"]

