version: '3'
# psql -t -l postgresql://ckan_default:Fearless@db/ckan_default
# https://docs.ckan.org/en/ckan-2.7.3/maintaining/configuration.html
# https://docs.ckan.org/projects/datapusher/en/latest/development.html
volumes:
  ckan:
  solr:
  postgres:

services:

  ckan:
    container_name: ckan
    image: ckan
    build:
      context: ./ckan/
    depends_on:
    - db
    - solr
    - redis
    - datapusher
    links:
    - db
    - solr
    - redis
    - datapusher
    ports:
    - 80:80
    environment:
    # Environment Specific
    - POSTGRES_HOST=db
    - SITE_URL=http://localhost
    - REDIS_URL=redis://redis:6379/1
    - REDIS_HOST=redis
    - SOLR_URL=http://solr:8983/solr/ckan
    - SOLR_HOST=solr
    - DATAPUSHER_HOST=datapusher
    - DATAPUSHER_URL=http://datapusher:8800
    # Secrets
    - POSTGRES_PASSWORD=fearless
    - SMTP_USR=fakeuser
    - SMTP_PWD=fakepass
    - APP_UUID=aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb
    - SESSION_SECRET=AAAAAAAAAAAAAAAAAAAAAAAAA
    ## To pull from AWS ParameterStore/SecretsManager, use the following:
    #- AWS_PROFILE=sba-upper
    #- POSTGRES_PASSWORD_PSID=/ckan/staging/db_password/postgres
    #- SMTP_USR_SMID=staging_SES_USER
    #- SMTP_PWD_SMID=staging_SES_PASSWORD
    #- APP_UUID_PSID=/ckan/staging/app_uuid
    #- SESSION_SECRET_PSID=/ckan/staging/session_secret
    volumes:
    - ~/.aws/:/root/.aws/
    - ckan:/var/lib/ckan/

  datapusher:
    container_name: datapusher
    image: ckan-datapusher
    build:
      context: ./ckan-datapusher/
    ports:
    - 8800
    environment:
    # Environment Specific
    - POSTGRES_HOST=db
    # Secrets
    - POSTGRES_PASSWORD=fearless

  db:
    container_name: postgres
    image: postgres:11.1
    environment:
    - POSTGRES_PASSWORD=fearless
    - POSTGRES_USER=ckan_default
    - POSTGRES_DB=ckan_default
    ports:
    - 5432
    volumes:
    - postgres:/var/lib/postgresql/data/

  solr:
    container_name: solr
    image: ckan-solr
    build:
      context: ./ckan-solr/
    ports:
    - 8983
    volumes:
    - solr:/opt/solr/server/solr/ckan/data/

  redis:
    container_name: redis
    image: redis:latest
    ports:
    - 6379
