version: '3'
# psql -t -l postgresql://ckan_default:Fearless@db/ckan_default
# https://docs.ckan.org/en/ckan-2.7.3/maintaining/configuration.html
# https://docs.ckan.org/projects/datapusher/en/latest/development.html
volumes:
  ckan:
  solr:
  postgres:

services:

  ckan:
    container_name: ckan
    image: ckan
    build:
      context: ./ckan/
    network_mode: host
#    depends_on:
#    - db
#    - solr
#    - redis
#    - datapusher
#    links:
#    - db
#    - solr
#    - redis
#    - datapusher
    ports:
    - 80:80
    expose:
    - 80
    environment:
    # Environment Specific
    - POSTGRES_FQDN=localhost
    - REDIS_FQDN=localhost
    - SOLR_FQDN=localhost
    - DATAPUSHER_FQDN=localhost
    - CKAN_SITE_URL=http://localhost
    - CKAN_SMTP_MAIL_TO=fake@e.mail
    - CKAN_SMTP_MAIL_FROM=fake@e.mail
    # (Optional) Defaults to 'email-smtp.us-east-1.amazonaws.com'
    - SMTP_FQDN=smtp.fake.mail
    # Secrets
    - POSTGRES_PASSWORD=fearless
    - CKAN_SMTP_USER=fake
    - CKAN_SMTP_PASSWORD=fake
    - APP_UUID=AAAAAAAA-0000-1111-2222-BBBBBBBBBBBB
    - SESSION_SECRET=AAAAAAAAAAAAAAAAAAAAAAAAA
    ## To pull from AWS ParameterStore/SecretsManager, use the following:
    - AWS_PROFILE=sba-upper
    #- POSTGRES_PASSWORD_PSID=/ckan/staging/db_password/postgres
    #- CKAN_SMTP_USER_SMID=staging_SES_USER
    #- SMTP_PWD_SMID=staging_SES_PASSWORD
    #- APP_UUID_PSID=/ckan/staging/app_uuid
    #- SESSION_SECRET_PSID=/ckan/staging/session_secret
    volumes:
    - ~/.aws/:/root/.aws/
    - ckan:/var/lib/ckan/

  datapusher:
    container_name: datapusher
    image: ckan-datapusher
    build:
      context: ./ckan-datapusher/
    network_mode: host
    ports:
    - 8800:8800
    expose:
    - 8080
    #extra_hosts:
    #- datapusher:0.0.0.0
    environment:
    # Environment Specific
    - DATAPUSHER_FQDN=localhost
  db:
    container_name: postgres
    image: postgres:11.1
    network_mode: host
    environment:
    - POSTGRES_PASSWORD=fearless
    - POSTGRES_USER=ckan_default
    - POSTGRES_DB=ckan_default
    ports:
    - 5432:5432
    expose:
    - 5432
    volumes:
    - postgres:/var/lib/postgresql/data/

  solr:
    container_name: solr
    image: ckan-solr
    network_mode: host
    build:
      context: ./ckan-solr/
    ports:
    - 8983:8983
    expose:
    - 8983
    volumes:
    - solr:/opt/solr/server/solr/ckan/data/

  redis:
    container_name: redis
    image: redis:latest
    network_mode: host
    ports:
    - 6379:6379
    expose:
    - 6379
