version: 2.1

executors:
  snyk:
    docker:
      - image: circleci/node

jobs:
  snykScanSolr:
    executor: snyk
    environment:
      IMAGE: ckan-solr
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Snyk
          command: sudo npm install -g snyk
      - deploy:
          name: Build Solr Container
          command: |
            cd solr
            docker image build -t $IMAGE .
      - deploy:
          name: Scan Solr Container
          command: snyk test --docker $IMAGE:latest --file=solr/Dockerfile

workflows:
  version: 2
  featureBranch:
    jobs:
      - snykScanSolr:
          context: snyk
          filters:
            branches:
              ignore:
                  - master
  masterBranch:
    jobs:
      - snykScanSolr:
          context: snyk
          filters:
            branches:
              only:
                  - master