name: Deploy CKAN
on:
  workflow_dispatch:
    inputs:
      target:
        type: environment
        required: true

defaults:
  run:
    shell: bash

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2
        id: ecr-login

      - name: Make ckan.ini
        env:
          CKAN_API_TOKEN: ${{ secrets.CKAN_API_TOKEN }}
          CKAN_SITE_URL: https://data.staging.ckan.ussba.io
          REDIS_URL: redis://redis.staging.ckan.ussba.io:6379/1
          SOLR_URL: http://solr.staging.ckan.ussba.io:8983/solr/ckan
        run: |
          sudo apt-get update -y
          sudo apt-get install gettext-base -y
          cd ckan/
          envsubst < ckan.ini.template > ckan.ini

      - name: ECR Build & Push CKAN
        uses: ./.github/actions/ecr
        with:
          dockerfile: ckan/Dockerfile
          image: ${{ steps.ecr-login.outputs.registry }}/ckan

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2
        id: ecr-login

      - name: Install Terraform 1.6.1
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.1'

      - name: Terraform Plan & Apply
        uses: ./.github/actions/terraform
        with:
          folder: ./terraform/applications
          image_tag: ${{ github.sha }}
          workspace: ${{ inputs.target }}
