name: 'Integration Tests'
on:
  push:
    branches-ignore:
      - 'master'

# Set the default shell for the build process.
# https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs
defaults:
  run:
    shell: 'bash'

# Set the build pipeline permissions.
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  contents: 'read' # used to checkout code
  id-token: 'write'

jobs:
  build-images:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: Pre Build Environment Substitute
        env:
          CKAN_API_TOKEN: ${{ secrets.CKAN_API_TOKEN }}
          CKAN_SITE_URL: https://data.staging.ckan.ussba.io
          REDIS_URL: redis://redis.staging.ckan.ussba.io:6379/1
          SOLR_URL: http://solr.staging.ckan.ussba.io:8983/solr/ckan
        run: |
          sudo apt-get update -y
          sudo apt-get install gettext-base -y
          cd ckan/
          envsubst < ckan.ini.template > ckan.ini

      - name: 'Docker Image Build CKAN'
        uses: './.github/actions/ecr'
        with:
          dockerfile: 'ckan/Dockerfile'
          image: 'ckan'
          push-to-ecr: false

      - name: 'Docker Image Build CKAN Solr'
        uses: './.github/actions/ecr'
        with:
          dockerfile: 'ckan-solr/Dockerfile'
          image: 'ckan-solr'
          push-to-ecr: false

  terraform:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Install Terraform 1.6.1'
        uses: 'hashicorp/setup-terraform@v2'
        with:
          terraform_version: '1.6.1'

      - name: 'Terraform Format'
        run: |
          cd terraform/
          terraform fmt -check -recursive

      # To run a terrafrom validate the project must be initialized, but we cannot use AWS credentials for integraton tests.
      # Remove the s3-backend.tf so that the project state will be initialized on the local container.
      - name: 'Terraform Validate'
        run: |
          cd terraform/applications
          rm s3-backend.tf
          terraform init -input=false
          terraform workspace new staging
          terraform validate
          terraform workspace new production
          terraform validate
